version: '3.7'

services:
  postgres:
    image: postgres:12.13
    container_name: "postgres"
    volumes:
      - "./postgres_scripts:/docker-entrypoint-initdb.d/"
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    hostname: postgres
    ports:
      - 5432:5432
    networks:
      - intranet      
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: "keycloak"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/import_folder/realm.json
      # JAVA_OPTS: -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dkeycloak.profile=preview
      # KEYCLOAK_LOGLEVEL: DEBUG
      # ROOT_LOGLEVEL: DEBUG
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    hostname: keycloak
    command:
      - start-dev
      - --http-port 8090
      - -Dkeycloak.profile=preview
      - -Dkeycloak.import=/tmp/import_folder/realm.json
    volumes:
      - "./import_folder/keycloak:/tmp/import_folder"
      - keycloak:/opt/keycloak/data
    ports:
      - 4000:4000
      - 8090:8090
    depends_on:
      - postgres
    networks:
      - intranet      
  external_idp:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: "external_idp"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: external_idp
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/import_folder/realm.json
      PROXY_ADDRESS_FORWARDING: "true"
      # JAVA_OPTS: -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dkeycloak.profile=preview
      #KEYCLOAK_LOGLEVEL: DEBUG
      #ROOT_LOGLEVEL: DEBUG
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    hostname: keycloak
    command:
      - start-dev
      - --http-port 8091
      - -Dkeycloak.profile=preview
      - -Dkeycloak.import=/tmp/import_folder/realm.json
    volumes:
      - "./import_folder/external_idp:/tmp/import_folder"
      - external_idp:/opt/keycloak/data
    ports:
      - 8091:8091
    depends_on:
      - postgres
    networks:
      - intranet      
  hydra:
    environment:
      - DSN=postgres://keycloak:password@postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SERVE_PUBLIC_CORS_ENABLED=true
      - SERVE_PUBLIC_CORS_ALLOWED_METHODS=POST,GET,PUT,DELETE
      - SERVE_ADMIN_CORS_ENABLED=true
      - SERVE_ADMIN_CORS_ALLOWED_METHODS=POST,GET,PUT,DELETE
    image: oryd/hydra:v2.0.2
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - ./import_folder/hydra:/etc/config/hydra
    restart: unless-stopped
    depends_on:
      - hydra-migrate
      - postgres
    hostname: hydra
    container_name: hydra
    networks:
      - intranet    
  hydra-migrate:
    environment:
      - DSN=postgres://keycloak:password@postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4      
    image: oryd/hydra:v2.0.2
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - ./import_folder/hydra:/etc/config/hydra
    restart: on-failure
    hostname: hydra-migrate
    container_name: hydra-migrate
    networks:
      - intranet    
  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v2.0.2
    ports:
      - "3000:3000"
    restart: unless-stopped
    hostname: consent
    container_name: consent
    networks:
      - intranet  
volumes:
  db:
    driver: local
  keycloak:
    driver: local
  external_idp:
    driver: local
networks:
  intranet:    